version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "monthly"
  labels:
  - "deps"
  commit-message:
    prefix: ci
  open-pull-requests-limit: 2
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  labels:
  - "deps"
  commit-message:
    prefix: ci
  open-pull-requests-limit: 2
