name: "CI"

on:
  push:
    branches:
      - $default-branch
    tags:
      - '*'
  pull_request:

permissions:
  contents: write



jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: "*"
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.2"
        install-go: false
    - name: Test Release
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: build --snapshot --single-target

  releaser:
    name: "Releaser"
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '*'
    - name: Install goreleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        install-only: true
    - name: Release
      run: goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}