name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: "*"
    - run: "go test -coverprofile=coverage.out -covermode=count ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.2"
        install-go: false
    - name: Test Release
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: build --snapshot --single-target
    - name: Patch Coverage
      uses: seriousben/go-patch-cover-action@first-version
      with:
        version: main