name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: "*"
    - run: "go test -v -coverprofile=coverage.out -covermode=count ./..."
      env:
        POSITRONIC_TEST_GITHUB_REPO: seriousben/positronic-blogger-git-api-playground
        POSITRONIC_TEST_GITHUB_TOKEN: ${{ secrets.POSITRONIC_TEST_GITHUB_TOKEN }}
        POSITRONIC_TEST_NEWSBLUR_USERNAME: ${{ secrets.POSITRONIC_TEST_NEWSBLUR_USERNAME }}
        POSITRONIC_TEST_NEWSBLUR_PASSWORD: ${{ secrets.POSITRONIC_TEST_NEWSBLUR_PASSWORD }}

    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        install-go: false
    - name: Test Release
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: build --snapshot --single-target
    - name: Patch Coverage
      uses: seriousben/go-patch-cover-action@v1
      with:
        version: main