name: "CI/CD"

on:
  push:
    branches:
      - $default-branch
  pull_request:

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: "*"
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.2"
        install-go: false
